import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavbarFB from "@/components/navbar/NavbarFB";
import {ApolloWrapper} from "@/lib/apollo-provider"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ApolloWrapper>

      <body className={inter.className}>
        <NavbarFB></NavbarFB>
        {children}
        </body>
      </ApolloWrapper>
    </html>
  );
}
